In [1]:
from dataset import *
from demo import *

running on CPU
running on CPU


In [2]:
args = get_args()

In [3]:
# random seed
manualSeed = 1

np.random.seed(manualSeed)
random.seed(manualSeed)
torch.manual_seed(manualSeed)

In [5]:
# 120 samples and 6 timepoints.
X = prepare_data(new_data=True,n_samples=120,n_times=6)

(120, 6, 35, 35, 4)


In [6]:
X = torch.from_numpy(X)
X = X.type(torch.FloatTensor)

In [7]:
table = np.zeros((args.num_folds - 1, args.num_timepoints))
table = random_table(args, 4/8)

In [8]:
print(table)

[[1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]


In [10]:
train(args,X[:, :, :, :, 0], table)

------------------------------------Fold [1/5]-----------------------------------------
-----------------------------------------------------------------------------
Ordering of the hospitals:  [3 2 1 0]
Epoch [1/60]
Hospital [4/4]
[Train] Loss T1: 1.22179 [Train] TP Loss T1: 1029.44795  [Train] Total Loss T1: 5147.85060 
Hospital [3/4]
[Train] Loss T1: 1.24068 [Train] TP Loss T1: 1074.96619  [Train] Total Loss T1: 5375.45127 
Hospital [2/4]
[Train] Loss T1: 1.29457 [Train] TP Loss T1: 1228.35232  [Train] Total Loss T1: 6142.40892 
Hospital [1/4]
[Train] Loss T1: 0.62551 [Train] TP Loss T1: 563.35402  [Train] Total Loss T1: 5634.16562 
Epoch [2/60]
Hospital [4/4]
[Train] Loss T1: 0.36086 [Train] TP Loss T1: 87.08272  [Train] Total Loss T1: 435.59401 
Hospital [3/4]
[Train] Loss T1: 0.35700 [Train] TP Loss T1: 84.09768  [Train] Total Loss T1: 420.66691 
Hospital [2/4]
[Train] Loss T1: 0.34148 [Train] TP Loss T1: 77.80627  [Train] Total Loss T1: 389.20208 
Hospital [1/4]
[Train] Loss T1:

KeyboardInterrupt: 